apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: iapteca
  labels:
    app: product-catalog
    app.kubernetes.io/name: product-catalog
    app.kubernetes.io/part-of: iapteca
    app.kubernetes.io/component: backend
spec:
  # ClusterIP: доступний лише всередині кластера (api-gateway проксує)
  type: ClusterIP
  selector:
    app: product-catalog
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
