apiVersion: v1
kind: Service
metadata:
  name: order-processing-service
  namespace: iapteca
  labels:
    app: order-processing
    app.kubernetes.io/name: order-processing
    app.kubernetes.io/part-of: iapteca
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: order-processing
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
